### ISSUE TITLE
Footnote IDs should not be the same as the Footnote Reference IDs

### ISSUE THREAD

**Issue by outlandnish** [remarkjs/remark-footnotes#2]
### Subject of the issue

I use remark + gatsbyjs to render content from Contentful. However, the resultant markup has the same id in DOM for the footnote reference as for the actual footnote. Because of this, the anchor link to the footnote does not work.

It looks like the markup for the footnote and the footnote reference are duplicated.

### Your environment

*   **OS**: Windows 10
*   **Packages**: `gatsbyjs`, `gatsby-transformer-remark`, `remark`
*   **Env**: Yarn: 1.21.1, NodeJS: v13.12.0, NPM: 6.14.4, Browser: Firefox 76.0

### Steps to reproduce

Live example: https://outlandnish.com/blog/eco-ish-hack-converting-my-car-to-use-e85-and-other-flex-fuels

* View markup for footnote reference 1 (after the text "because I can't stop myself")
* Click footnote reference link
* View markup for footnote 1

### Expected behaviour

ID for footnote 1 should be **"fn-1"**. Href back to the footnote reference should be **"fnref-1"**

### Actual behaviour

ID for footnote 1 is **"fnref-1"**. Href back to the footnote reference is **"fn-1"**

**Comment by outlandnish** [comment]
I'm an idiot, I had the wrong syntax for the the footnotes and it was treating it as a reference. Sorry and please disregard!

**Comment by wooorm** [comment]
You're not an idiot, you just made a mistake ;) 👋

**Comment by outlandnish** [comment]
Haha you're too kind!

**Comment by TovlyDeutsch** [comment]
@outlandnish Would you be able to post your old (incorrect) and new (correct) markdown examples? I'm also using Gatsby and remark and am having the same issue. With this markdown:

`Some text in post body[^1] more text [^1] actual footnote`

I get this html output:

```
Some text in post body
<sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup>
more text
<sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup>
````

The output of both parts of the footnote are identical and therefore they don't link to one another (only to the first one).

**Comment by TovlyDeutsch** [comment]
Never mind, I figured out the issue. Colons after the footnote definition are mandatory (e.g. `[^1]:`), I thought they were just a stylistic choice.
