### ISSUE TITLE
Footnote Links should not simply replicate reference tag

### ISSUE THREAD

**Issue by jhull** [remarkjs/remark-footnotes#3]
As per [Markdown Syntax](https://www.markdownguide.org/extended-syntax/#footnotes), footnotes references should automatically default to consecutive numbers. For example, this:

```
This is a sentence.[^1] And this is another interesting sentence.[^notes]

[^1]: some additional information
[^notes]: And here are some more notes
```

Should output footnote links like this:

```
1. some additional information
2. And here are some more notes
```
The current implementation simply grabs the original reference, and uses that as the anchor tag.

This is not standard across all other Markdown Footnotes implementations, and thus breaks many pages that previously worked.

**Comment by wooorm** [comment]
Cm you expand on your last paragraph?

**Comment by jhull** [comment]
I have a lot of content with Footnotes where I used "words" as references, instead of a sequence of numbers. This was fine in the past because previous implementations would transform those word references into a sequence of numbers. Now those words are showing up as the actual links within documents.

Here is an example of [a broken page](https://narrativefirst.com/articles/on-dramaticas-extraordinary-sense-of-perception/). You can see there are several footnote references that now appear as words - words I didn't expect anyone to see. 

They're listed correctly at the bottom - just the links to them needs to reflect those numbers.

**Comment by wooorm** [comment]
> previous implementations

Can you expand on which ones those were?

**Comment by jhull** [comment]
By previous implementations I meant other Markdown plugins in other contexts, spec. markdown-it-footnotes.

In addition, every app that considers Markdown Footnotes does this automatically (iaWriter, Ulysses, etc.). It's industry standard to handle footnotes this way.

**Comment by wooorm** [comment]
> It's industry standard to handle footnotes this way.

That’s a bold statement; I think it’s more nuanced, as there is no standard for footnotes in Markdown. I’ve found that every parser works differently.

---

I like that footnotes have meaningful labels. It allows alpha, roman, or even the typical `*, †, ‡, §, |, ¶`.

See [`remark-numbered-footnote-labels`](https://github.com/jackfletch/remark-numbered-footnote-labels) (and the project it’s based on, linked there) to use numbers instead.

**Comment by smontlouis** [comment]
@wooorm  As of today it looks like now the plugin displays number instead of reference by default. Is it possible to display the reference instead ?

**Comment by wooorm** [comment]
Can you expand on your use case: input/actual/expected, etc?

**Comment by smontlouis** [comment]
@wooorm sorry if I wasn't clear. I would like to have the footnote links to replicate reference tag.

Expected:

```
This is a sentence.[^a] And this is another interesting sentence.[^b]

[^a]: some additional information
[^b]: And here are some more notes
```

To output footnote links like this:

```
a. some additional information
b. And here are some more notes
```


Today:

```
This is a sentence.[^a] And this is another interesting sentence.[^b]

[^a]: some additional information
[^b]: And here are some more notes
```

To output footnote links like this:

```
1. some additional information
2. And here are some more notes
```

**Comment by wooorm** [comment]
Can you expand on why?
To add, the output you expect was never the actual output: the list at the end was always a list and the numbers controlled by CSS.

**Comment by smontlouis** [comment]
Oh sorry I thought it was like that before, I must have misunderstood the issue.
This is what my client would like to have, but I can convince him otherwise if it's not available.
