### ISSUE TITLE
Please support inline footnotes for markdown-it-footnote.

### ISSUE THREAD

**Issue by Mister-Hope** [remarkjs/remark-footnotes#5]
### Subject of the feature

`markdown-it-footnote` suppots inline footnote.

See https://github.com/markdown-it/markdown-it-footnote

```md
Here is an inline note.^[Inlines notes are easier to write, since
you don't have to pick an identifier and move down to type the
note.]
```

### Problem

When using inline footnote, ` Found reference to undefined definition` error is triggered,

### Expected behavior

No errors.

**Comment by wooorm** [comment]
This is supported and documented in the readme
