### ISSUE TITLE
Make footnotes accessible

### ISSUE THREAD

**Issue by robinmetral** [remarkjs/remark-footnotes#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The markup generated by `remark-footnotes` is not accessible.

For example, it's missing a footnotes section label, `aria-describedby` attributes on footnote links to let SR users know the link is to a footnote.

### Solution

We can follow @KittyGiraudel's advice from their blog post about accessible footnotes: https://www.sitepoint.com/accessible-footnotes-css/

Happy to discuss further and help out with any implementation.

### Alternatives

SC users are confused by footnotes 😕

**Comment by wooorm** [comment]
I believe this is already in place, just not updated in the readme.
It landed here: https://github.com/syntax-tree/mdast-util-to-hast/commit/0260f76983b342c74b6a29f36f5ab612859334de.

**Comment by wooorm** [comment]
Updated the docs to reflect the changes in `remark-rehype`/`mdast-util-to-hast`!

**Comment by robinmetral** [comment]
🎉 amazing! Thanks @wooorm. Will suggest an upgrade in [Astro](https://github.com/snowpackjs/astro)

**Comment by robinmetral** [comment]
I think this is a good first step, but I've tested this with VoiceOver (no NVDA at hand unfortunately 😕) and it doesn't seem like Pandoc's markup is ideal. Are you open to me suggesting further improvements to it in `mdast-util-to-hast` @wooorm? Happy to write up some kind of RFC for it

**Comment by wooorm** [comment]
Sure!
It would be preferable to stick with some standard, perhaps changing it in Pandoc too. and it depends on what the changes are. But I’m definitely interested in better accessibility!
