### ISSUE TITLE
Footnotes should link to their contexts/usage

### ISSUE THREAD

**Issue by AlbinoGeek** [remarkjs/remark-footnotes#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Once a user has clicked `1` to scroll down to the first footnote and read it, they have no way to return to the context of where they had clicked that footnote. Wikipedia and many other reference lists offer an arrow or caret (often the power symbol) `^` which, when clicked, returns the user to the passage the footnote was sourced from.

### Solution

![image](https://user-images.githubusercontent.com/1910461/132069372-0edee005-c30f-4b6c-9be8-b9d614fc042c.png)
See: [References section on the Wikipedia page for Exemplum](https://en.wikipedia.org/wiki/Exemplum#References)

The small power/caret symbols `^` are links to the first (or only) use of each noted reference.

---

Further, when a footnote is referenced multiple times, the power/caret is not a link, but instead followed by latin letter links:

![image](https://user-images.githubusercontent.com/1910461/132069510-06291c4e-2b82-47f3-8595-13d93c7f74f2.png)
See: [Wikipedia page for United States](https://en.wikipedia.org/wiki/United_States)

### Alternatives

While I can get fairly close to Wikipedia's citation format by abusing a BibTeX parser, I cannot add the context backlink.

I am already using `rehypeSlug` and have confirmed it is slugging the reference's source, so there is an existing anchor that could be linked to by this plugin.

![image](https://user-images.githubusercontent.com/1910461/132069666-965f0cf7-1369-4d64-aac8-7d3951a514aa.png)

---

I also might be using the wrong plugin for this! (remark/rehype ecosystem is confusing for first-time users, hundreds of high level plugins which duplicate functionality found in low level plugins and visa-versa.)

**Comment by wooorm** [comment]
There is a backlink though? 🤔 (see the readme, do you have different output?)

**Comment by AlbinoGeek** [comment]
Apologies! The dangling `↩` character does return to the first instance.

My request now boils down to when a reference is used multiple times, such as shown above.

Current behaviour is to scroll to the first reference, not the reference that took you there (nor are multiple return arrows drawn.)

**Comment by wooorm** [comment]
Pandoc “handles” this by adding the same definition multiple times: https://pandoc.org/try/?text=Here+is+a+footnote+reference%2C%5B%5E1%5D%0Aanother%2C%5B%5E1%5D.%0A%0A%5B%5E1%5D%3A+Here+is+the+footnote.%0A%0A&from=markdown&to=&standalone=0.
I’m not sure how great that is.

But I also don’t think that Wikipedia’s way is great: there’s no way of knowing at the bottom whether I came from a/b/c/d and so which one will take me “home”? 🤔

Aside: I think the `↩` should probably have an `aria-label="Jump up"` added.

/cc also @robinmetral from https://github.com/remarkjs/remark-footnotes/issues/6 who might have ideas on the accessibility of this.

**Comment by AlbinoGeek** [comment]
I believe there is also aria labeled-by and aria described-by that might
apply here.

**Comment by wooorm** [comment]
Yes, but I don’t see how Wikipedia’s way works nicely for either assistive touch users, or users like myself that don’t use those tools? `aria-labeled-by` will set up a link, but what it references remains the number of the footnote that they all share.?

Say we have a large document with many references to the same footnote (`x`):

```markdown
Lorem ipsum dolor sit amet[^x], consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua[^x]. ...
```

```html
<p>
  Lorem ipsum dolor sit amet,<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua<a href="#fn1" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>1</sup></a>
  ...
</p>
...
<section class="footnotes" role="doc-endnotes">
  <hr>
  <ol>
    <li id="fn1" role="doc-endnote">
      <p>
        Here is the footnote.
        ↩
        <a href="#fnref1" class="footnote-back" role="doc-backlink">a</a>
        <a href="#fnref2" class="footnote-back" role="doc-backlink">b</a>
        ...
      </p>
    </li>
  </ol>
</section>
```

**Comment by wooorm** [comment]
https://twitter.com/wooorm/status/1443624547937308675

GH does solve your backlinks things
